import type { TableauWorkbook } from '../../parsers/model.js';

export interface WorkbookEntry {
  workbook: TableauWorkbook;
  slug: string;
}

export function generateAppTsx(entries: WorkbookEntry[]): string {
  const imports = entries.map((e) =>
    `import { Dashboard as ${toPascalCase(e.slug)}Dashboard } from './workbooks/${e.slug}/Dashboard'`
  ).join('\n');

  const routes = entries.map((e) =>
    `        <Route path="/${e.slug}" element={<${toPascalCase(e.slug)}Dashboard />} />`
  ).join('\n');

  return `import { Routes, Route } from 'react-router-dom'
${imports}
import { WorkbookList } from './WorkbookList'

export function App() {
  return (
    <Routes>
      <Route path="/" element={<WorkbookList />} />
${routes}
    </Routes>
  )
}
`;
}

export function generateWorkbookListTsx(entries: WorkbookEntry[]): string {
  const cards = entries.map((e) => {
    const wb = e.workbook;
    const summary = wb.executiveSummary ? `\n          <p style={{ fontSize: 10, color: '#64748b', marginTop: 4, lineHeight: 1.5 }}>${escJsx(wb.executiveSummary.slice(0, 120))}${wb.executiveSummary.length > 120 ? '…' : ''}</p>` : '';
    return `      <a href="/${e.slug}" onClick={(ev) => { ev.preventDefault(); navigate('/${e.slug}') }} style={{ display: 'block', textDecoration: 'none', background: 'white', border: '1px solid #e2e8f0', borderRadius: 8, padding: '16px 20px', transition: 'box-shadow 0.15s' }} onMouseEnter={(e) => (e.currentTarget.style.boxShadow = '0 4px 12px rgba(0,0,0,0.08)')} onMouseLeave={(e) => (e.currentTarget.style.boxShadow = '')}>
        <h2 style={{ fontSize: 14, fontWeight: 600, color: '#0f172a' }}>${escJsx(wb.metadata.name)}</h2>${summary}
        <p style={{ fontSize: 10, color: '#94a3b8', marginTop: 8 }}>${wb.worksheets.length} worksheets · ${wb.dataSources.length} data source${wb.dataSources.length === 1 ? '' : 's'}</p>
      </a>`;
  }).join('\n');

  return `import { useNavigate } from 'react-router-dom'

export function WorkbookList() {
  const navigate = useNavigate()
  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: '2rem 1.5rem', fontFamily: "'Poppins', sans-serif" }}>
      <h1 style={{ fontSize: 21, fontWeight: 700, color: '#0f172a', marginBottom: 4 }}>Dashboards</h1>
      <p style={{ fontSize: 10, color: '#94a3b8', marginBottom: 24 }}>
        Generated by <a href="https://github.com/raguvindtharanitharan/drexo" style={{ color: '#3b82f6', textDecoration: 'none' }}>drexo</a>
      </p>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
${cards}
      </div>
    </div>
  )
}
`;
}

function toPascalCase(slug: string): string {
  return slug.split('-').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

function escJsx(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/'/g, '&#39;').replace(/"/g, '&quot;');
}

